In [61]:
#Import modules
import numpy as np
import pandas as pd
import random

In [62]:
def load_data(file_path):
    return pd.read_excel(file_path)#.dropna().reset_index(drop=True)

def get_sitetimes_list(decal):
    full_set = set()
    for lst in decal["Availabilities"]:
        for item in lst:
            full_set.add(item.strip())
    return full_set

def ohe_availabilities(decal, sitetimes):
    availbilities = decal['Availabilities']
    new_df = pd.DataFrame()
    for time in sitetimes:
        ohe = []
        for person in availbilities:
            ohe.append(time in person)
        new_df[time] = ohe
    full_df = decal.join(new_df)
    return full_df

def add_fake_drivers(full_df):
    lst = []
    for i in range(full_df.shape[0]):
        lst.append(random.random() <= 0.3)
    full_df["Driver"] = lst
    return full_df

In [63]:
#Clean Decal Dataset
decal = load_data(r"data\DeCal Availability Confirmation (Responses).xlsx").rename(columns = {"To help us have the most updated information when making rearrangements, please check all times you are available to go to site. Remember to leave 30 minutes before and after for site transportation.":"Availabilities"})
decal['Availabilities'] = decal['Availabilities'].str.split(", ")
decal = add_fake_drivers(decal)

In [64]:
decal[decal['Name'] == "Parker Lum"]

,Timestamp,Name,Can you make the site time you have been assigned?,Availabilities,Email Address,Driver
7,2023-01-30 19:29:07.575,Parker Lum,Yes,"[Tuesday 3:30-4:30pm, Tuesday 3:45-4:45pm, Tue...",NaN,True

In [65]:
#Get Sitetimes
sitetimes = get_sitetimes_list(decal)

#Clean SL Dataset
sl = load_data(r"data\SL Availability Sp 23 (Responses).xlsx").rename(columns = {"Please select all times you are available to lead a site.":"Availabilities", "Do you have access to a car that seats 5 people, including yourself, that you can drive to site? OR Are you willing and able to rent a Gig/Zipcar/etc. to drive to site?":"Driver"})

#Clean Staff Dataset
staff = load_data(r"data\Staff Availability Sp 23 (Responses).xlsx").rename(columns = {"Please select all times you are available to go to site.":"Availabilities","Are you willing and able to rent a Gig/Zipcar/etc. to drive to site?":"Driver"})
staff = staff[["Name","Email Address","Availabilities","Driver"]]

In [66]:
full_df = ohe_availabilities(decal, sitetimes)
full_df = full_df.drop(columns = ["Timestamp","Can you make the site time you have been assigned?","Availabilities"])

full_df[full_df['Name'] == "Parker Lum"]

,Name,Email Address,Driver,Wednesday 3:00-4:00pm,Tuesday 5:00-6:00pm,Wednesday 2:00-3:00pm,Thursday 12:00-1:00pm,Tuesday 4:00-5:00pm,Thursday 3:30-4:30pm,Thursday 10:55-11:55am,Wednesday 3:30-4:30pm,Wednesday 5:00-6:00pm,Friday 1:30-2:30pm,Friday 1:40-2:40pm,Thursday 4:00-5:00pm,Friday 9:20-10:20am,Tuesday 3:45-4:45pm,Thursday 4:30-5:30pm,Wednesday 4:00-5:00pm,Tuesday 3:30-4:30pm
7,Parker Lum,NaN,True,False,True,False,False,True,False,False,False,False,False,False,False,False,True,False,False,True

In [67]:
sl_df = ohe_availabilities(sl, sitetimes)
sl_df = sl_df.drop(columns = ["Timestamp","Availabilities","What was the date of your most recent Tuberculosis test and clearance? (Leave blank if N/A)"])
sl_df.head()

,Email Address,Name,Driver,Wednesday 3:00-4:00pm,Tuesday 5:00-6:00pm,Wednesday 2:00-3:00pm,Thursday 12:00-1:00pm,Tuesday 4:00-5:00pm,Thursday 3:30-4:30pm,Thursday 10:55-11:55am,Wednesday 3:30-4:30pm,Wednesday 5:00-6:00pm,Friday 1:30-2:30pm,Friday 1:40-2:40pm,Thursday 4:00-5:00pm,Friday 9:20-10:20am,Tuesday 3:45-4:45pm,Thursday 4:30-5:30pm,Wednesday 4:00-5:00pm,Tuesday 3:30-4:30pm
0,puertajared@berkeley.edu,Jared Puerta,No,False,False,False,False,False,True,True,True,False,False,False,False,True,True,True,False,True
1,marinelyden@berkeley.edu,Marine Lyden,No,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,andrewtshih@berkeley.edu,Andrew Shih,Yes,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,shaniyur@berkeley.edu,Surabhi Haniyur,No,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True
4,vincentxlee@berkeley.edu,Vincent,No,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False

In [68]:
staff_df = ohe_availabilities(staff, sitetimes)
staff_df = staff_df.drop(columns = ["Availabilities"])
staff_df.head()

,Name,Email Address,Driver,Wednesday 3:00-4:00pm,Tuesday 5:00-6:00pm,Wednesday 2:00-3:00pm,Thursday 12:00-1:00pm,Tuesday 4:00-5:00pm,Thursday 3:30-4:30pm,Thursday 10:55-11:55am,Wednesday 3:30-4:30pm,Wednesday 5:00-6:00pm,Friday 1:30-2:30pm,Friday 1:40-2:40pm,Thursday 4:00-5:00pm,Friday 9:20-10:20am,Tuesday 3:45-4:45pm,Thursday 4:30-5:30pm,Wednesday 4:00-5:00pm,Tuesday 3:30-4:30pm
0,Emily Yepez,emilyyepez@berkeley.edu,No,False,False,False,False,False,True,False,False,False,True,True,False,False,False,False,False,False
1,Johnny Luu,johnnyluu@berkeley.edu,Yes,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
2,Charlie Juster,c.juster@berkeley.edu,No,False,False,False,False,False,False,True,True,False,True,True,False,False,False,False,False,False
3,Safaa Mouline,safaamouline@berkeley.edu,No,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
4,Nicole Xin,nicolexin@berkeley.edu,No,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [69]:
staff_df.to_csv("Staff.csv")
sl_df.to_csv("SL.csv")

In [70]:
staff_names = set(staff['Name'].tolist())
sl_names = set(sl['Name'].tolist())
full_staff_names = staff_names.union(sl_names)
full_staff_names

{'Aditya Murali',
 'Akshara Vykunta',
 'Alvie Kam',
 'Amrita Rajan',
 'Andrew Shih',
 'Anooj Desai',
 'Ashley Kaya',
 'Carina Kim',
 'Charlie Juster',
 'Daniel Detchev',
 'Ekansh Agrawal',
 'Emily Yepez',
 'Gaby Tan',
 'Hailey Adams',
 'Hannah Chou',
 'Ingrid Altunin',
 'Jacob Yim',
 'Jared Puerta',
 'Jeong Hoon (Jay) Kim',
 'Johnny Luu',
 'Kaitlin Corpus ',
 'Kaitlyn Wang',
 'Kenneth Suhaili',
 'Lucy Gleeson',
 'Marine',
 'Marine Lyden',
 'Neil Kamdar',
 'Nicole Xin',
 'Patricia Suwardi',
 'Safaa Mouline',
 'Sunay Dagli',
 'Surabhi Haniyur',
 'Vincent',
 'rishi'}

In [71]:
criteria = []
for name in full_df['Name']:
    criteria.append(name not in full_staff_names)
decal_df = full_df[criteria]
decal_df

,Name,Email Address,Driver,Wednesday 3:00-4:00pm,Tuesday 5:00-6:00pm,Wednesday 2:00-3:00pm,Thursday 12:00-1:00pm,Tuesday 4:00-5:00pm,Thursday 3:30-4:30pm,Thursday 10:55-11:55am,Wednesday 3:30-4:30pm,Wednesday 5:00-6:00pm,Friday 1:30-2:30pm,Friday 1:40-2:40pm,Thursday 4:00-5:00pm,Friday 9:20-10:20am,Tuesday 3:45-4:45pm,Thursday 4:30-5:30pm,Wednesday 4:00-5:00pm,Tuesday 3:30-4:30pm
0,Kyle Kishimoto,NaN,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
1,Shlok Rajurkar,NaN,False,False,False,False,True,False,True,True,False,False,False,False,True,False,False,True,False,False
2,Terry Yesung Han,NaN,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
3,Audrey Lim,NaN,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
5,Sanjana Fernando,NaN,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,Michael Cui,michael_cui@berkeley.edu,False,True,False,True,True,False,True,True,True,True,False,False,True,False,False,True,True,False
92,Nicholas Lu,Nicholas.lu@berkeley.edu,True,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True
93,Evelyn Batchelor,eeb2622@berkeley.edu,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
94,Rebecca Bernstein,rebeccabernstein@berkeley.edu,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False
95,Owen Donayre,odonayre25@berkeley.edu,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False

In [72]:
decal_df.to_csv("Decal.csv")

In [73]:
df = pd.read_csv('Decal.csv').drop(columns = "Unnamed: 0").reset_index()
df.head()

,index,Name,Email Address,Driver,Wednesday 3:00-4:00pm,Tuesday 5:00-6:00pm,Wednesday 2:00-3:00pm,Thursday 12:00-1:00pm,Tuesday 4:00-5:00pm,Thursday 3:30-4:30pm,...,Wednesday 3:30-4:30pm,Wednesday 5:00-6:00pm,Friday 1:30-2:30pm,Friday 1:40-2:40pm,Thursday 4:00-5:00pm,Friday 9:20-10:20am,Tuesday 3:45-4:45pm,Thursday 4:30-5:30pm,Wednesday 4:00-5:00pm,Tuesday 3:30-4:30pm
0,0,Kyle Kishimoto,NaN,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
1,1,Shlok Rajurkar,NaN,False,False,False,False,True,False,True,...,False,False,False,False,True,False,False,True,False,False
2,2,Terry Yesung Han,NaN,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,3,Audrey Lim,NaN,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,4,Sanjana Fernando,NaN,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [74]:
df = df.set_index("index").iloc[:,3:].T
df

index,0,1,2,3,4,5,6,7,8,9,...,73,74,75,76,77,78,79,80,81,82
Wednesday 3:00-4:00pm,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,False,False
Tuesday 5:00-6:00pm,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Wednesday 2:00-3:00pm,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False
Thursday 12:00-1:00pm,False,True,False,False,False,False,False,False,False,True,...,False,False,False,False,True,True,False,False,False,False
Tuesday 4:00-5:00pm,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Thursday 3:30-4:30pm,False,True,True,True,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
Thursday 10:55-11:55am,False,True,False,False,False,False,False,True,False,False,...,False,False,False,False,False,True,False,False,False,True
Wednesday 3:30-4:30pm,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,True,False,False,False,False
Wednesday 5:00-6:00pm,False,False,False,False,True,False,False,False,False,False,...,False,True,False,True,False,True,False,False,False,False
Friday 1:30-2:30pm,False,False,False,False,False,False,False,False,True,False,...,True,False,True,False,False,False,False,False,False,False
Friday 1:40-2:40pm,True,False,False,False,False,False,False,False,True,False,...,True,False,True,False,False,False,False,False,False,False
Thursday 4:00-5:00pm,False,True,False,False,False,True,False,False,False,False,...,False,False,False,False,False,True,False,False,True,False
Friday 9:20-10:20am,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
Tuesday 3:45-4:45pm,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
Thursday 4:30-5:30pm,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
Wednesday 4:00-5:00pm,False,False,False,False,False,False,False,False,False,False,...,True,True,False,False,False,True,False,False,False,False
Tuesday 3:30-4:30pm,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [75]:
df[df[1]].index.to_list()

['Thursday 12:00-1:00pm',
 'Thursday 3:30-4:30pm',
 'Thursday 10:55-11:55am',
 'Thursday 4:00-5:00pm',
 'Thursday 4:30-5:30pm']